news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.titulo a'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.c_t a'