news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.titulo a'
      article_body: '.field-name-body'
      article_title: 'h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.c_t a'
      article_body: '.a_c'
      article_title: '.a_t'