news_sites:
  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.titulo a'
      article_body: '.field-name-body'
      article_title: 'h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.c_t a'
      article_body: '.a_c'
      article_title: '.a_t'
  elchiguirebipolar:
    url: https://www.elchiguirebipolar.net
    queries:
      homepage_article_links: '.cbp-article__wrapper'
      article_body: '.single__article__main__content'
      article_title: '.single__article__header__title'